- name: debug
  debug:
    msg: "Jestee libvirte instance"

- name: debug
  debug:
    var: instance

- include_tasks: terraform.yml

- name: wait for vms to get ip addr
  vars:
    new_instance: "{{ instance|combine({
      'value': {
        'counter': counter,
        'name': iac.name+'-'+instance.key+'-'+counter|string,
        }
      }
      ,recursive=True) }}"
  shell: |
    set -o pipefail
    virsh -c {{ lookup('env', 'QEMU_URI')|default('qemu:///system', true) }} domifaddr --domain {{ new_instance.value.name }} --source agent --interface eth0 |tail -n+3|head -n1|awk '{print $4}'|cut -f1 -d/
  loop: "{{ range(0, instance.value.count|int)|list }}"
  loop_control:
    loop_var: counter
  register: reg_ip
  until: reg_ip.stdout
  environment:
    LIBVIRT_DEFAULT_URI: "qemu:///system"
  #  become: True
  retries: 10
  changed_when: False
  check_mode: False
- name: wait 5 sec for sure
  pause:
    seconds: 5

- name: ips
  debug:
    var: reg_ip
