- name: debug
  debug:
    msg: "Jestee libvirte instance"

- name: debug
  debug:
    var: instance

- name: create vm
  vars:
    new_instance: "{{ instance|combine({
      'value': {
        'counter': counter,
        'name': 'exphost-'+instance.key+'-'+counter|string,
        }
      }
      ,recursive=True) }}"
  include_tasks: create.yml
  loop: "{{ range(0, instance.value.count|int)|list }}"
  loop_control:
    loop_var: counter

- name: debug
  debug:
    var: created_vms

- name: wait for vms to get ip addr
  shell: "virsh domifaddr {{ item }} |tail -n+3|head -n1|awk '{print $4}'|cut -f1 -d/"
  loop: "{{ created_vms|default([]) }}"
  register: reg_ip
  until: "{{ reg_ip.stdout != '' }}"
  environment:
    LIBVIRT_DEFAULT_URI: "qemu:///system"
  #  become: True
  retries: 10
  changed_when: False

- name: ips
  debug:
    var: reg_ip

    #- include_tasks: add_hosts_to_inventory.yml
