---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - stat:
        path: "{{terraform_tmp_path}}/{{item}}"
      loop: "{{iac.hosts|list}}"
      register: existing_test_paths
      #- debug:
      #    msg: "{{existing_test_paths}}"
    - terraform:
        binary_path: "{{terraform_path}}"
        project_path: "{{terraform_tmp_path}}/{{item.item}}"
        state: absent
      when: item.stat.exists
      loop: "{{existing_test_paths.results}}"
